#+TITLE: Starter Kit Gnus -- IMAP
#+OPTIONS: num:nil ^:nil
#+STARTUP: hideblocks

Based on the instructions at [[http://www.emacswiki.org/emacs/GnusGmail#toc2][emacswiki:GnusGmail]].

* saving mail locally
Where your mail will be saved locally default value will be =~/gmail=.
#+begin_src emacs-lisp
  (setq nnml-directory "~/gmail")
  (setq message-directory "~/gmail")
#+end_src

All Gmail groups will be ignored by the default value of
=gnus-ignored-newsgroups=, so let's change that default value.
#+begin_src emacs-lisp
  (setq gnus-ignored-newsgroups "^to\\.\\|^[0-9. ]+\\( \\|$\\)\\|^[\”]\”[#’()]")
#+end_src

* getting mail
Set Gmail as the primary source for incoming mail (Gnus can aggregate
many email and/or newsgroup sources).
#+begin_src emacs-lisp
  (setq gnus-select-method
        '(nnimap "gmail"
                 (nnimap-address "imap.gmail.com")
                 (nnimap-server-port 993)
                 (nnimap-stream ssl)))
#+end_src

Place a line like the following in =~/.authinfo=
#+begin_src fundamental :tangle ~/.authinfo
  machine imap.gmail.com login your-name@gmail.com password your-password port 993
#+end_src

and make sure that no-one else can read it with
#+begin_src sh
  chmod 600 ~/.authinfo
#+end_src

* sending mail
/Requirement/: gnus uses the [[http://en.wikipedia.org/wiki/STARTTLS][starttls]] tool for encrypted sending of
email to the Gmail SMTP server.  This is easily installed on modern
Debian (including Ubuntu) systems with
#+begin_src sh
  apt-get install starttls
#+end_src

The following configures gnus to use the Gmail SMTP server for sending
email.
#+begin_src emacs-lisp
  (setq message-send-mail-function 'smtpmail-send-it
        smtpmail-starttls-credentials '(("smtp.gmail.com" 587 nil nil))
        smtpmail-auth-credentials '(("smtp.gmail.com" 587 "your-name@gmail.com" nil))
        smtpmail-default-smtp-server "smtp.gmail.com"
        smtpmail-smtp-server "smtp.gmail.com"
        smtpmail-smtp-service 587)
#+end_src

If you don't want to be prompted for a password on every mail sent,
you can add the following line to your =~/.authinfo=.
#+begin_src fundamental :tangle ~/.authinfo
  machine smtp.gmail.com login your-name@gmail.com your-password secret port 587
#+end_src
* using this file

1) tangle this file :: Run the =org-babel-tangle= command to extract
   the code embedded in this file into a =gnu-gmail.el= file which can
   be added to your configuration, and a =~/.authinfo= file which will
   be used by gnus.

2) load this configuration :: If you have a recent version of Org-mode
   (i.e. after 7.0) or are using the [[http://eschulte.github.com/emacs-starter-kit/][literate Emacs Starter Kit]], then
   this file can be loaded directly using the =org-babel-load-file=
   function, or by placing it in your load path (if you're using the
   starter kit).
     
   Alternately ensure that the =gnus-gmail.el= file generated by the
   previous step is loaded by your configuration.

3) fire up gnus :: This can be done with the command =M-x gnus=

4) view your mail :: After gnus boots up you will see the "Group
   Buffer" (see [[http://www.gnu.org/software/emacs/manual/html_node/gnus/index.html#toc_Group-Buffer][Group-Buffer]]).  Each line is a mail "Group", hit
   =SPACE= or =ENTER= on a group to view it's contents.  You should
   see an "INBOX" group which contains the mail in your gmail
   account.  If not, you can jump to the "INBOX" group by
     - pressing =j= for "jump"
     - tab completing the name "INBOX"
     - pressing =U= for "unkill" meaning this will now always be
       displayed in your Group buffer when you have new mail

5) customize :: Gnus has unrivalled capacity for customization.  Once
   your comfortable with basic usage, take some time to browse through
   the very readable [[http://www.gnu.org/software/emacs/manual/html_node/gnus/index.html][Gnus Manual]] to learn untold tricks.
