<h2>CLEO Memorandum Assignment #1. What&apos;s Next?</h2>
<table cellpadding="0" cellspacing="0">
	<thead>
		<tr>
			<th class="first author">Activity</th>
<!--			<th class="time">Progress</th> -->
		</tr>
	</thead>

	<tbody>
		<?php
		$AM = $this->activity_model; 
		foreach ($this->focus_transitions as $tran => $satisfied) {
			$props = $AM->getTransitionProps($tran);
			$url_params = $props['url_params'];
			$link_text = $props['link_text'];
			if (null !== $url_params and null !== $link_text) {
				// TODO Add $sat class to <td>, style accordingly.
		?>
			<tr>
				<td class="first author"><a href="<?= 
					$this->url($url_params) ?>"><?= $link_text ?></a></td>
<!--				<td><?=
				// TODO $props['allotted']
				$satisfied ? '&#x2714;' : '&nbsp;'
				?></td> -->
			</tr>
		<?php }} ?>
	</tbody>
</table>
<!--
<?php
print_r($this->acts);
print_r($this->states);
print_r($this->payload);
print_r($this->activity_model);
?>
-->
<?php
$foo = <<<MY_FOO
I am a heredoc
MY_FOO;
?>
